/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as EditProductIdRouteImport } from './routes/edit-product.$id'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard.overview'
import { Route as CreatorsUsernameRouteImport } from './routes/creators.$username'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DashboardCreatorIndexRouteImport } from './routes/dashboard.creator.index'
import { Route as DashboardCreatorWithdrawalsRouteImport } from './routes/dashboard.creator.withdrawals'
import { Route as DashboardCreatorWithdrawalHistoryRouteImport } from './routes/dashboard.creator.withdrawal-history'
import { Route as DashboardCreatorProfileRouteImport } from './routes/dashboard.creator.profile'
import { Route as DashboardCreatorOrdersRouteImport } from './routes/dashboard.creator.orders'
import { Route as DashboardCreatorMyProductsRouteImport } from './routes/dashboard.creator.my-products'
import { Route as DashboardCreatorEarningsRouteImport } from './routes/dashboard.creator.earnings'
import { Route as DashboardCreatorCustomersRouteImport } from './routes/dashboard.creator.customers'
import { Route as DashboardCreatorAnalyticsRouteImport } from './routes/dashboard.creator.analytics'
import { Route as DashboardCreatorAddProductRouteImport } from './routes/dashboard.creator.add-product'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProductIdRoute = EditProductIdRouteImport.update({
  id: '/edit-product/$id',
  path: '/edit-product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/dashboard/overview',
  path: '/dashboard/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsUsernameRoute = CreatorsUsernameRouteImport.update({
  id: '/creators/$username',
  path: '/creators/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const DashboardCreatorIndexRoute = DashboardCreatorIndexRouteImport.update({
  id: '/dashboard/creator/',
  path: '/dashboard/creator/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreatorWithdrawalsRoute =
  DashboardCreatorWithdrawalsRouteImport.update({
    id: '/dashboard/creator/withdrawals',
    path: '/dashboard/creator/withdrawals',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCreatorWithdrawalHistoryRoute =
  DashboardCreatorWithdrawalHistoryRouteImport.update({
    id: '/dashboard/creator/withdrawal-history',
    path: '/dashboard/creator/withdrawal-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCreatorProfileRoute = DashboardCreatorProfileRouteImport.update({
  id: '/dashboard/creator/profile',
  path: '/dashboard/creator/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreatorOrdersRoute = DashboardCreatorOrdersRouteImport.update({
  id: '/dashboard/creator/orders',
  path: '/dashboard/creator/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreatorMyProductsRoute =
  DashboardCreatorMyProductsRouteImport.update({
    id: '/dashboard/creator/my-products',
    path: '/dashboard/creator/my-products',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCreatorEarningsRoute =
  DashboardCreatorEarningsRouteImport.update({
    id: '/dashboard/creator/earnings',
    path: '/dashboard/creator/earnings',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCreatorCustomersRoute =
  DashboardCreatorCustomersRouteImport.update({
    id: '/dashboard/creator/customers',
    path: '/dashboard/creator/customers',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCreatorAnalyticsRoute =
  DashboardCreatorAnalyticsRouteImport.update({
    id: '/dashboard/creator/analytics',
    path: '/dashboard/creator/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCreatorAddProductRoute =
  DashboardCreatorAddProductRouteImport.update({
    id: '/dashboard/creator/add-product',
    path: '/dashboard/creator/add-product',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/blog': typeof BlogRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/creators/$username': typeof CreatorsUsernameRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/edit-product/$id': typeof EditProductIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/creator/add-product': typeof DashboardCreatorAddProductRoute
  '/dashboard/creator/analytics': typeof DashboardCreatorAnalyticsRoute
  '/dashboard/creator/customers': typeof DashboardCreatorCustomersRoute
  '/dashboard/creator/earnings': typeof DashboardCreatorEarningsRoute
  '/dashboard/creator/my-products': typeof DashboardCreatorMyProductsRoute
  '/dashboard/creator/orders': typeof DashboardCreatorOrdersRoute
  '/dashboard/creator/profile': typeof DashboardCreatorProfileRoute
  '/dashboard/creator/withdrawal-history': typeof DashboardCreatorWithdrawalHistoryRoute
  '/dashboard/creator/withdrawals': typeof DashboardCreatorWithdrawalsRoute
  '/dashboard/creator/': typeof DashboardCreatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/blog': typeof BlogRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/creators/$username': typeof CreatorsUsernameRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/edit-product/$id': typeof EditProductIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/creator/add-product': typeof DashboardCreatorAddProductRoute
  '/dashboard/creator/analytics': typeof DashboardCreatorAnalyticsRoute
  '/dashboard/creator/customers': typeof DashboardCreatorCustomersRoute
  '/dashboard/creator/earnings': typeof DashboardCreatorEarningsRoute
  '/dashboard/creator/my-products': typeof DashboardCreatorMyProductsRoute
  '/dashboard/creator/orders': typeof DashboardCreatorOrdersRoute
  '/dashboard/creator/profile': typeof DashboardCreatorProfileRoute
  '/dashboard/creator/withdrawal-history': typeof DashboardCreatorWithdrawalHistoryRoute
  '/dashboard/creator/withdrawals': typeof DashboardCreatorWithdrawalsRoute
  '/dashboard/creator': typeof DashboardCreatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/blog': typeof BlogRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/creators/$username': typeof CreatorsUsernameRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/edit-product/$id': typeof EditProductIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/creator/add-product': typeof DashboardCreatorAddProductRoute
  '/dashboard/creator/analytics': typeof DashboardCreatorAnalyticsRoute
  '/dashboard/creator/customers': typeof DashboardCreatorCustomersRoute
  '/dashboard/creator/earnings': typeof DashboardCreatorEarningsRoute
  '/dashboard/creator/my-products': typeof DashboardCreatorMyProductsRoute
  '/dashboard/creator/orders': typeof DashboardCreatorOrdersRoute
  '/dashboard/creator/profile': typeof DashboardCreatorProfileRoute
  '/dashboard/creator/withdrawal-history': typeof DashboardCreatorWithdrawalHistoryRoute
  '/dashboard/creator/withdrawals': typeof DashboardCreatorWithdrawalsRoute
  '/dashboard/creator/': typeof DashboardCreatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/affiliates'
    | '/blog'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/downloads'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/marketplace'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/blog/$slug'
    | '/creators/$username'
    | '/dashboard/overview'
    | '/edit-product/$id'
    | '/products/$id'
    | '/dashboard/'
    | '/dashboard/creator/add-product'
    | '/dashboard/creator/analytics'
    | '/dashboard/creator/customers'
    | '/dashboard/creator/earnings'
    | '/dashboard/creator/my-products'
    | '/dashboard/creator/orders'
    | '/dashboard/creator/profile'
    | '/dashboard/creator/withdrawal-history'
    | '/dashboard/creator/withdrawals'
    | '/dashboard/creator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/affiliates'
    | '/blog'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/downloads'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/marketplace'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/blog/$slug'
    | '/creators/$username'
    | '/dashboard/overview'
    | '/edit-product/$id'
    | '/products/$id'
    | '/dashboard'
    | '/dashboard/creator/add-product'
    | '/dashboard/creator/analytics'
    | '/dashboard/creator/customers'
    | '/dashboard/creator/earnings'
    | '/dashboard/creator/my-products'
    | '/dashboard/creator/orders'
    | '/dashboard/creator/profile'
    | '/dashboard/creator/withdrawal-history'
    | '/dashboard/creator/withdrawals'
    | '/dashboard/creator'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/affiliates'
    | '/blog'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/downloads'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/marketplace'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/blog/$slug'
    | '/creators/$username'
    | '/dashboard/overview'
    | '/edit-product/$id'
    | '/products/$id'
    | '/dashboard/'
    | '/dashboard/creator/add-product'
    | '/dashboard/creator/analytics'
    | '/dashboard/creator/customers'
    | '/dashboard/creator/earnings'
    | '/dashboard/creator/my-products'
    | '/dashboard/creator/orders'
    | '/dashboard/creator/profile'
    | '/dashboard/creator/withdrawal-history'
    | '/dashboard/creator/withdrawals'
    | '/dashboard/creator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AffiliatesRoute: typeof AffiliatesRoute
  BlogRoute: typeof BlogRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CreatorsUsernameRoute: typeof CreatorsUsernameRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  EditProductIdRoute: typeof EditProductIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCreatorAddProductRoute: typeof DashboardCreatorAddProductRoute
  DashboardCreatorAnalyticsRoute: typeof DashboardCreatorAnalyticsRoute
  DashboardCreatorCustomersRoute: typeof DashboardCreatorCustomersRoute
  DashboardCreatorEarningsRoute: typeof DashboardCreatorEarningsRoute
  DashboardCreatorMyProductsRoute: typeof DashboardCreatorMyProductsRoute
  DashboardCreatorOrdersRoute: typeof DashboardCreatorOrdersRoute
  DashboardCreatorProfileRoute: typeof DashboardCreatorProfileRoute
  DashboardCreatorWithdrawalHistoryRoute: typeof DashboardCreatorWithdrawalHistoryRoute
  DashboardCreatorWithdrawalsRoute: typeof DashboardCreatorWithdrawalsRoute
  DashboardCreatorIndexRoute: typeof DashboardCreatorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-product/$id': {
      id: '/edit-product/$id'
      path: '/edit-product/$id'
      fullPath: '/edit-product/$id'
      preLoaderRoute: typeof EditProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$username': {
      id: '/creators/$username'
      path: '/creators/$username'
      fullPath: '/creators/$username'
      preLoaderRoute: typeof CreatorsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/dashboard/creator/': {
      id: '/dashboard/creator/'
      path: '/dashboard/creator'
      fullPath: '/dashboard/creator/'
      preLoaderRoute: typeof DashboardCreatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creator/withdrawals': {
      id: '/dashboard/creator/withdrawals'
      path: '/dashboard/creator/withdrawals'
      fullPath: '/dashboard/creator/withdrawals'
      preLoaderRoute: typeof DashboardCreatorWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creator/withdrawal-history': {
      id: '/dashboard/creator/withdrawal-history'
      path: '/dashboard/creator/withdrawal-history'
      fullPath: '/dashboard/creator/withdrawal-history'
      preLoaderRoute: typeof DashboardCreatorWithdrawalHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creator/profile': {
      id: '/dashboard/creator/profile'
      path: '/dashboard/creator/profile'
      fullPath: '/dashboard/creator/profile'
      preLoaderRoute: typeof DashboardCreatorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creator/orders': {
      id: '/dashboard/creator/orders'
      path: '/dashboard/creator/orders'
      fullPath: '/dashboard/creator/orders'
      preLoaderRoute: typeof DashboardCreatorOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creator/my-products': {
      id: '/dashboard/creator/my-products'
      path: '/dashboard/creator/my-products'
      fullPath: '/dashboard/creator/my-products'
      preLoaderRoute: typeof DashboardCreatorMyProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creator/earnings': {
      id: '/dashboard/creator/earnings'
      path: '/dashboard/creator/earnings'
      fullPath: '/dashboard/creator/earnings'
      preLoaderRoute: typeof DashboardCreatorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creator/customers': {
      id: '/dashboard/creator/customers'
      path: '/dashboard/creator/customers'
      fullPath: '/dashboard/creator/customers'
      preLoaderRoute: typeof DashboardCreatorCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creator/analytics': {
      id: '/dashboard/creator/analytics'
      path: '/dashboard/creator/analytics'
      fullPath: '/dashboard/creator/analytics'
      preLoaderRoute: typeof DashboardCreatorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creator/add-product': {
      id: '/dashboard/creator/add-product'
      path: '/dashboard/creator/add-product'
      fullPath: '/dashboard/creator/add-product'
      preLoaderRoute: typeof DashboardCreatorAddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AffiliatesRoute: AffiliatesRoute,
  BlogRoute: BlogRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CreatorsUsernameRoute: CreatorsUsernameRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  EditProductIdRoute: EditProductIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCreatorAddProductRoute: DashboardCreatorAddProductRoute,
  DashboardCreatorAnalyticsRoute: DashboardCreatorAnalyticsRoute,
  DashboardCreatorCustomersRoute: DashboardCreatorCustomersRoute,
  DashboardCreatorEarningsRoute: DashboardCreatorEarningsRoute,
  DashboardCreatorMyProductsRoute: DashboardCreatorMyProductsRoute,
  DashboardCreatorOrdersRoute: DashboardCreatorOrdersRoute,
  DashboardCreatorProfileRoute: DashboardCreatorProfileRoute,
  DashboardCreatorWithdrawalHistoryRoute:
    DashboardCreatorWithdrawalHistoryRoute,
  DashboardCreatorWithdrawalsRoute: DashboardCreatorWithdrawalsRoute,
  DashboardCreatorIndexRoute: DashboardCreatorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
